# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PGP-Mail
version:      1.7
version_from: Mail.pm
installdirs:  site
requires:
    GnuPG::Interface:              0
    MIME::Tools:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
